### ISSUE TITLE
Npm install fails when run with cygwin.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#100]
When trying to install dependencies with `npm install`  with cygwin the install fails with 
```npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\hbowden\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:nogsmpls/react-docgen.git C:\Users\hbowden\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nogsmpls-react-docgen-git-feature-inferDisplayName-79ab8115
npm ERR! Cloning into bare repository 'C:\Users\hbowden\AppData\Roaming\npm-cache\_git-remotes\git-github-com-nogsmpls-react-docgen-git-feature-inferDisplayName-79ab8115'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

However running `npm install` in MINGW32 works just fine.

**Comment by NogsMPLS** [comment]
I thiiiiiink this can be easily fixed, but yes, this is because of react-component-styleguide dependency. specifically this line:

https://github.com/NogsMPLS/react-component-styleguide/blob/master/package.json#L107

Basically the reason that is like that is because i was trying to get react-docgen to infer the displayName of any react component, whether class, createClass or stateless functional component. But now there might be an actual solution:

https://github.com/reactjs/react-docgen/pull/59#issuecomment-246020403

react-docgen has transitioned to a  plugin system. go to:

https://github.com/nerdlabs/react-docgen-displayname-handler

and see if you can integrate that into react-component-styleguide.

**Comment by NogsMPLS** [comment]
This will require you to update react-docgen in package.json, add react-docgen-displayname-handler in package.json.

for code to edit i would look first at https://github.com/NogsMPLS/react-component-styleguide/blob/master/lib/webpack-plugins/ReactDocgenPlugin.js 

and see how the handler might be able to get plugged into there.

**Comment by hbowden** [comment]
No longer an issue.
