### ISSUE TITLE
Allow Link button text to be any case.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#596]
So maybe an uppercase prop that defaults off, a lowercase prop that defaults off, and have default be honor the case that is passed in ?

**Comment by stuller** [comment]
or a textTransform prop that defaults to uppercase (since that follows styleguide) but would allow lowercase, capitalize, none, or inherit as well?

**Comment by hbowden** [comment]
@stuller If the style guide defaults to uppercase and we think that's fine for UX we should make that the default and like you said allow for lowercase, mixed case, etc, via props. What do you think @Darper ?

**Comment by Darper** [comment]
Styleguide pattern for Link button is to keep the case the user enters (see below). I'm not opposed to passing props, but default should be no transform.

![image](https://user-images.githubusercontent.com/6515956/36756651-46d92d82-1bd5-11e8-9029-19d951eb0d91.png)

**Comment by stuller** [comment]
oh yeah, sorry.  i didn't notice this was for the link button as opposed to normal buttons.  
So it looks like the way it is now, both are displaying according to styleguide.  Since user can pass in both className and style, is there a need for a specific prop for this?

speaking as a user, i generally have a css class i assign to all my buttons anyway, and text transform is usually part of that, because it's easier to change if a redesign has to happen than it is to go in and manually change all the button text.

**Comment by stuller** [comment]
Derek says this is complete.
